MvcStore/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Store.DataAccess.Data;
using Store.DataAccess.Repository;
using Store.DataAccess.Repository.IRepository;
using Store.Models;
using Store.Models.ViewModel;
using Store.Utility;


namespace Mystore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;

        public CompanyController(IUnitOfWork UnitOfWork)
        {
            _UnitOfWork = UnitOfWork;

        }
        public IActionResult Index()
        {
            List<Company> ObjCompanyList = _UnitOfWork.company.GetAll().ToList();


            return View(ObjCompanyList);
        }
        public IActionResult Upsert(int? id)
        {

            if (id == null || id == 0)
                return View(new Company());
            else
            {
                Company companyobj = _UnitOfWork.company.Get(u => u.Id == id);
                return View(companyobj);
            }
        }

        [HttpPost]

        public IActionResult Upsert(Company companyobj)
        {
            //if (obj.Name == obj.DisplayOrder.ToString())
            //{
            //    ModelState.AddModelError("name", "the DisplayOrder cannot ");
            //}
            if (ModelState.IsValid)
            {

                if (companyobj.Id == 0)
                    _UnitOfWork.company.Add(companyobj);
                else
                    _UnitOfWork.company.Update(companyobj);
                _UnitOfWork.Save();
                TempData["Succes"] = "Company created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View(companyobj);
            }

        }

        //public IActionResult Edit(int? id)
        //{
        //	if (id == null)
        //	{
        //		return NotFound();
        //	}
        //	//Category? category = _db.Categories.Where(c => c.Id == id).FirstOrDefault();

        //	Company? Company = _UnitOfWork.Company.Get(c => c.Id == id);
        //	//Category category = _db.Categories.Find(id);

        //	if (Company == null)
        //	{
        //		return NotFound();
        //	}
        //	return View(Company);
        //}

        //[HttpPost]
        //public IActionResult Edit(Company obj)
        //{

        //	if (ModelState.IsValid)
        //	{
        //		_UnitOfWork.Company.Update(obj);
        //		_UnitOfWork.Save();
        //		TempData["Succes"] = "Company Edited successfully";

        //		return RedirectToAction("Index");
        //	}
        //	return View();
        //}
        //public IActionResult Delete(int? id)
        //{
        //	if (id == null)
        //	{
        //		return NotFound();
        //	}
        //	//Category? category = _db.Categories.Where(c => c.Id == id).FirstOrDefault();

        //	Company? Company = _UnitOfWork.Company.Get(c => c.Id == id);
        //	//Category category = _db.Categories.Find(id);

        //	if (Company == null)
        //	{
        //		return NotFound();
        //	}
        //	return View(Company);
        //}

        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeletePost(int? id)
        //{

        //	Company obj = _UnitOfWork.Company.Get(c => c.Id == id);
        //	if (obj == null)
        //	{
        //		return NotFound();
        //	}
        //	_UnitOfWork.Company.Remove(obj);
        //	_UnitOfWork.Save();
        //	TempData["Succes"] = "Company Deleteed successfully";
        //	return RedirectToAction("Index");

        //}

        [HttpGet]

        public IActionResult GetAll()
        {
            List<Company> ObjCompanyList = _UnitOfWork.company.GetAll().ToList();

            return Json(new { data = ObjCompanyList });
        }

        [HttpDelete]

        public IActionResult Delete(int? id)
        {

            var CompanyToDeleted = _UnitOfWork.company.Get(c => c.Id == id);
            if (CompanyToDeleted == null)
            {
                return Json(new { success = false, Message = "Error while deleting" });
            }



            _UnitOfWork.company.Remove(CompanyToDeleted);
            _UnitOfWork.Save();
            //List<Company> ObjCompanyList = _UnitOfWork.company.GetAll(includeproperties: "Category").ToList();

            return Json(new { success = true, Message = "deleting successfully" });
        }
    }

}

MvcStore/Areas/Admin/Views/Company/Index.cshtml
<div class="container">
	<div class="row pt-4 pb-3">
		<div class="col-6">
			<h2 class="text-primary">
				Company List
			</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
				<i class="bi bi-plus-circle-dotted"></i> Create New Company
			</a>
		</div>
	</div>
	<table id="myuTable" class="table table-bordered table-striped" style="width:100%">
	<thead>
	 <tr>
		<th>  Name</th>
		<th>City</th>
		<th>StreetAddress</th>
	    <th>PostalCode</th>
		<th>State</th>
		<th>  Phone Number</th>
				@* 
		 <th>
			Description
		 </th>
				 *@
				
				@* <th>
					CategoryId
				</th> *@
			@* 	<th>
					List Price
				</th> *@
				
			@* 	<th>
					Price50
				</th>
				<th>
					Price100
				</th> *@
				
	 </tr>
	</thead>
	
    </table>

</div>
@section Scripts{
	<script src="~/js/company.js"></script>

}

MvcStore/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<form method="post" enctype="multipart/form-data">
	<input asp-for="Id" hidden />
	
	<div class="row">
		<div class="col-12" >

			<div class="border p-3 mt-4">
				<div class="row pb-2">
					<h2 class="text-primary">
						@(Model.Id != 0 ? "Update " : "Create ")Company
						<hr />
					</h2>
				</div>
				<div asp-validation-summary="ModelOnly"></div>

				<div class="mb-2 row p-1">
					<label asp-for="Name" class="p-0"></label>
					<input asp-for="Name" class=" form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="mb-2 row">
					<label asp-for="City" class="p-0"> </label>
					<input asp-for="City" class=" form-control" />
					<span asp-validation-for="City" class="text-danger"></span>
				</div>
				<div class="mb-2 row p-1">
					<label asp-for="StreetAddress" class="p-0"></label>
					<input asp-for="StreetAddress" class=" form-control" />
					<span asp-validation-for="StreetAddress" class="text-danger"></span>
				</div>
				<div class="mb-2 row">
					<label asp-for="PostalCode" class="p-0"> </label>
					<input asp-for="PostalCode" class=" form-control" />
					<span asp-validation-for="PostalCode" class="text-danger"></span>
				</div>
				<div class="mb-2 row p-1">
					<label asp-for="State" class="p-0"></label>
					<input asp-for="State" class=" form-control" />
					<span asp-validation-for="State" class="text-danger"></span>
				</div>
				<div class="mb-2 row">
					<label asp-for="PhoneNumber" class="p-0"> </label>
					<input asp-for="PhoneNumber" class=" form-control" />
					<span asp-validation-for="PhoneNumber" class="text-danger"></span>
				</div>
				
				
				<div class="row p-2">
					<div class="col-6 col-md-3">

						@if (Model.Id != 0)
						{
							<button type="submit" class="btn btn-primary form-control">Update</button>
						}
						else
						{
							<button type="submit" class="btn btn-primary form-control">Create</button>
						}
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="Company" asp-action="Index" class="btn btn-secondary form-control">
							Back to List
						</a>
					</div>

				</div>
			</div>

		</div>
		
	</div>
	
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
} 